FROM nginx:1.27.0-bookworm

# ------------------------- SECURE SOCKET LAYER -------------------------
# Install OpenSSL
RUN mkdir -p /etc/nginx/ssl
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y openssl
RUN apt install -y dos2unix

# Configure NGINX by overwritting configuration file
COPY config/nginx.conf /etc/nginx/nginx.conf

# ------------------------- LOG LAYER -----------------------------------
# install logstash to add log in aetheryte
RUN apt install -y wget gpg systemctl
RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elastic-keyring.gpg
RUN apt install apt-transport-https
RUN echo "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-8.x.list
RUN apt update
RUN apt install -y logstash
RUN unlink /var/log/nginx/access.log
RUN systemctl enable logstash
RUN mkdir /etc/logstash/pattern

COPY config/logNginx.conf /etc/logstash/conf.d 
COPY /config/launchLogstash.sh /docker-entrypoint.d/
COPY config/gen-certificate.sh /docker-entrypoint.d/

RUN dos2unix /docker-entrypoint.d/launchLogstash.sh
RUN chmod +x /docker-entrypoint.d/launchLogstash.sh

RUN dos2unix /docker-entrypoint.d/gen-certificate.sh
RUN chmod +x /docker-entrypoint.d/gen-certificate.sh

# Exposes port 443 and makes it available only for inter-container communication (required for SSL protocol)
EXPOSE 443