FROM debian:bookworm

RUN apt update -y
RUN apt upgrade -y
RUN apt install -y openssl dos2unix

COPY config/gen-certificate.sh /config/gen-certificate.sh

RUN dos2unix config/gen-certificate.sh
RUN chmod +x /config/gen-certificate.sh