networks:
    transcendence:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1

volumes:
    # API Gateway
    aetheryte_postgres:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: aetheryte_api_gateway/docker/volumes/data
    # Tournament
    tournament_postgres_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: tournament/docker/volumes/data

services:
    # Aetheryte API Gateway
    aetheryte-nginx:
        extends:
            file: aetheryte_api_gateway/docker/docker-compose.yml
            service: aetheryte-nginx
        depends_on:
            aetheryte-python:
                condition: service_healthy
        ports:
            # - "80:80"
            - "10444:443"
    aetheryte-postgres:
        extends:
            file: aetheryte_api_gateway/docker/docker-compose.yml
            service: aetheryte-postgres
    aetheryte-python:
        extends:
            file: aetheryte_api_gateway/docker/docker-compose.yml
            service: aetheryte-python
        depends_on:
            aetheryte-postgres:
                condition: service_healthy

    # Frontend - User interface
    ui-nginx:
        extends:
            file: frontend-ui/docker/docker-compose.yml
            service: ui-nginx
        ports:
            - "10443:443"

    # Pong
    pong-python:
        extends:
            file: pong/docker/docker-compose.yml
            service: pong-python
        ports:
            - "9000:9000"

    # Tournament
    tournament-postgres:
        extends:
            file: tournament/docker/docker-compose.yml
            service: tournament-postgres
    tournament-python:
        extends:
            file: tournament/docker/docker-compose.yml
            service: tournament-python
        depends_on:
            tournament-postgres:
                condition: service_healthy