networks:
    transcendence:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1

volumes:
    # API Gateway
    aetheryte_postgres:
        driver: local
    # Tournament
    tournament_postgres_volume:
        driver: local
 
    # Live chat
    livechat_postgres_volume:
        driver: local

services:
    # Aetheryte API Gateway
    aetheryte-nginx:
        extends:
            file: aetheryte_api_gateway/docker/docker-compose.yml
            service: aetheryte-nginx
        depends_on:
            aetheryte-python:
                condition: service_healthy
        ports:
            - "10444:443"
    aetheryte-postgres:
        extends:
            file: aetheryte_api_gateway/docker/docker-compose.yml
            service: aetheryte-postgres
    aetheryte-python:
        extends:
            file: aetheryte_api_gateway/docker/docker-compose.yml
            service: aetheryte-python
        depends_on:
            aetheryte-postgres:
                condition: service_healthy

    # Frontend - User interface
    ui-nginx:
        extends:
            file: frontend-ui/docker/docker-compose.yml
            service: ui-nginx
        ports:
            - "10443:443"

    # # Pong
    pong-python:
        extends:
            file: pong/docker/docker-compose.yml
            service: pong-python
        ports:
            - "9000:9000"

    # Tournament
    tournament-python:
        extends:
            file: livechat/docker/docker-compose.yml
            service: livechat-python
        ports:
            - "8000:8000"
        depends_on:
            aetheryte-postgres:
                condition: service_healthy

    # Live chat
    livechat-postgres:
        extends:
            file: livechat/docker/docker-compose.yml
            service: livechat-postgres
    livechat-python:
        extends:
            file: livechat/docker/docker-compose.yml
            service: livechat-python
        ports:
            - "8000:8000"
        depends_on:
            livechat-postgres:
                condition: service_healthy