# Generated by Django 5.0.6 on 2024-09-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player_1_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_2_score',
        ),
    ]
