# Generated by Django 5.0.6 on 2024-09-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservice', '0002_remove_match_player_1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.IntegerField(default=3),
        ),
    ]
