# Generated by Django 5.0.6 on 2024-09-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microservice', '0003_tournament_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_datetime',
        ),
    ]
