services:
    tournament-postgres:
        build:
            context: postgres
            dockerfile: Dockerfile
        volumes:
            - tournament_postgres_volume:/var/lib/postgresql/data/
        networks:
            transcendence:
                ipv4_address: 172.20.2.3
        environment:
            POSTGRES_DB: ${TOURNAMENT_POSTGRES_NAME}
            POSTGRES_USER: ${ROOT_USER}
            POSTGRES_PASSWORD: ${ROOT_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${ROOT_USER} -d ${TOURNAMENT_POSTGRES_NAME}'"]
            interval: 10s
            timeout: 5s
            retries: 10
        restart: unless-stopped

    tournament-python:
        build:
            context: python
            dockerfile: Dockerfile
        networks:
            transcendence:
                ipv4_address: 172.20.2.2
        environment:
            TOURNAMENT_POSTGRES_DB: ${TOURNAMENT_POSTGRES_NAME}
            TOURNAMENT_POSTGRES_USER: ${ROOT_USER}
            TOURNAMENT_POSTGRES_PASSWORD: ${ROOT_PASSWORD}
            TOURNAMENT_POSTGRES_IP: ${TOURNAMENT_POSTGRES_IP}
            TOURNAMENT_POSTGRES_PORT: ${TOURNAMENT_POSTGRES_PORT}
            TOURNAMENT_DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        volumes:
            - ../app/:/app/
        # healthcheck:
        #     test: curl --fail http://localhost:10000/tournament/remote || exit 1
        #     interval: 10s
        #     timeout: 5s
        #     retries: 10
        restart: on-failure