services:
    ui-nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        networks:
            - transcendence
        volumes:
            - ../app/:/var/www/html/
        environment:
            NGINX_HOST: "localhost"
            NGINX_PORT: "443"
        healthcheck:
            test: curl --fail https://localhost/ || exit 1
            interval: 10s
            timeout: 5s
            retries: 5
        restart: on-failure
