services:
    livechat-postgres:
        build:
            context: postgres
            dockerfile: Dockerfile
        volumes:
            - livechat_postgres_volume:/var/lib/postgresql/data/
            - ../app/:/app/
        networks:
            transcendence:
                ipv4_address: 172.20.5.3
        environment:
            POSTGRES_DB: ${LIVECHAT_POSTGRES_DB}
            POSTGRES_USER: ${LIVECHAT_POSTGRES_USER}
            POSTGRES_PASSWORD: ${LIVECHAT_POSTGRES_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${LIVECHAT_POSTGRES_USER} -d ${LIVECHAT_POSTGRES_DB}'"]
            interval: 10s
            timeout: 5s
            retries: 10
        restart: unless-stopped

    livechat-python:
        build:
            context: python
            dockerfile: Dockerfile
        networks:
            transcendence:
                ipv4_address: 172.20.5.2
        volumes:
            - ../app/:/app/
        # healthcheck:
        #     test: curl --fail https://172.20.5.2:8000/ || exit 1
        #     interval: 10s
        #     timeout: 5s
        #     retries: 10
        restart: on-failure