FROM nginx:1.27.0-bookworm

# ------------------------- SECURE SOCKET LAYER -------------------------
# Install OpenSSL
RUN mkdir -p /etc/nginx/ssl
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y openssl

# Generate SSL certificate (req for request / -x509 for self-signed / -nodes for non encrypted private key)
RUN openssl req -x509 -nodes \
			-out /etc/nginx/ssl/certificate.crt \
			-keyout /etc/nginx/ssl/private.key \
			-subj "/C=SW/ST=VD/L=Lausanne/O=42-transcendence/CN=172.20.0.4"

# Configure NGINX by overwritting configuration file
COPY config/aetheryte.conf /etc/nginx/nginx.conf

# ------------------------- LOG LAYER -----------------------------------
# install logstash to add log in aetheryte
RUN apt install -y wget gpg systemctl
RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elastic-keyring.gpg
RUN apt install apt-transport-https
RUN echo "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-8.x.list
RUN apt update
RUN apt install -y logstash
RUN unlink /var/log/nginx/access.log
RUN systemctl enable logstash
RUN mkdir /etc/logstash/pattern

COPY config/logNginx.conf /etc/logstash/conf.d 
COPY /config/launchLogstash.sh /docker-entrypoint.d/

# Exposes port 443 and makes it available only for inter-container communication (required for SSL protocol)
EXPOSE 443