FROM nginx:1.27.0-bookworm

# ------------------------- SECURE SOCKET LAYER -------------------------
# Install OpenSSL
RUN mkdir -p /etc/nginx/ssl
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y openssl

# Generate SSL certificate (req for request / -x509 for self-signed / -nodes for non encrypted private key)
RUN openssl req -x509 -nodes \
			-out /etc/nginx/ssl/certificate.crt \
			-keyout /etc/nginx/ssl/private.key \
			-subj "/C=SW/ST=VD/L=Lausanne/O=42-transcendence/CN=172.20.0.4"

# Configure NGINX by overwritting configuration file
COPY config/aetheryte.conf /etc/nginx/nginx.conf

# Exposes port 443 and makes it available only for inter-container communication (required for SSL protocol)
EXPOSE 443