# Generated by Django 5.0.7 on 2024-08-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='senderName',
        ),
    ]
