# Generated by Django 5.0.7 on 2024-09-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blacklist',
        ),
    ]
