# Generated by Django 4.1.13 on 2024-09-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='joiner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
