# Generated by Django 4.1.13 on 2024-09-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong_app', '0002_games_mode_alter_games_joiner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='looser_id',
            new_name='loser_id',
        ),
    ]
