# Generated by Django 5.0.6 on 2024-07-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userverification_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='doubleAuthActive',
            field=models.BooleanField(default=False),
        ),
    ]
