# Generated by Django 5.0.6 on 2024-07-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
