# Generated by Django 5.0.6 on 2024-09-03 08:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
