# Generated by Django 5.0.6 on 2024-09-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_customuser_friends_list_customuser_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
