services:
    user-management-postgres:
        build:
            context: postgres
            dockerfile: Dockerfile
        volumes:
            - user_management_postgres_volume:/var/lib/postgresql/data/
            - ../app/:/app/
        networks:
            transcendence:
                ipv4_address: 172.20.1.3
        environment:
            POSTGRES_DB: ${USERS_POSTGRES_DB}
            POSTGRES_USER: ${USERS_POSTGRES_USER}
            POSTGRES_PASSWORD: ${USERS_POSTGRES_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${USERS_POSTGRES_USER} -d ${USERS_POSTGRES_DB}'"]
            interval: 10s
            timeout: 5s
            retries: 10
        restart: unless-stopped

    user-management-python:
        build:
            context: python
            dockerfile: Dockerfile
        networks:
            transcendence:
                    ipv4_address: 172.20.1.2
        # Volumes supplémentaire à rajouter si on met les photos de profil j'imagine?
        volumes:
            - ../app/:/app/
        healthcheck:
            test: curl --fail https://172.20.1.2:8000/ || exit 1
            interval: 10s
            timeout: 5s
            retries: 10
        restart: on-failure