services:
    pong-python:
        build:
            context: python
            dockerfile: Dockerfile
        networks:
            - transcendence
        volumes:
            - ../app/:/app/
        healthcheck:
            test: curl --fail https://localhost:8000/ || exit 1
            interval: 10s
            timeout: 5s
            retries: 5
        restart: on-failure